# backend/tests/test_contract.py
"""
API contract guard: exposed routes, documentation and openapi.json synchronization.

Any change to a route or HTTP method now requires explicitly updating the tests and the
versioned openapi.json files (generated by `python export_openapi.py`).
"""

import json
import os

import pytest

from main import app

BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(BACKEND_DIR)

EXPECTED_ROUTES = {
    "/api/users": {"get", "post"},
    "/api/users/{user_id}": {"get", "delete"},
    "/api/hosts": {"get", "post"},
    "/api/hosts/{host_id}": {"delete"},
}


def test_openapi_exposes_exactly_the_expected_routes():
    paths = app.openapi()["paths"]

    assert set(paths) == set(EXPECTED_ROUTES)
    for route, methods in EXPECTED_ROUTES.items():
        assert set(paths[route]) == methods


@pytest.mark.parametrize("relative_path", ["backend/openapi.json", "openapi.json"])
def test_versioned_openapi_files_are_in_sync(relative_path):
    path = os.path.join(REPO_ROOT, relative_path)
    assert os.path.exists(path), f"Versioned OpenAPI file not found: {path}"

    with open(path, encoding="utf-8") as file:
        versioned = json.load(file)

    def route_map(schema):
        return {route: sorted(methods) for route, methods in schema["paths"].items()}

    assert route_map(versioned) == route_map(app.openapi())


def test_interactive_documentation_is_available(client):
    assert client.get("/openapi.json").status_code == 200

    response = client.get("/docs")
    assert response.status_code == 200
    assert "swagger" in response.text.lower()
